"""Add Watch model

Revision ID: 0b99c81da941
Revises: 01faad862048
Create Date: 2025-07-19 21:32:20.959393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b99c81da941'
down_revision = '01faad862048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=False),
    sa.Column('watched_on', sa.Date(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watches')
    # ### end Alembic commands ###
