"""Add profile_picture to User model

Revision ID: 81df6892ff08
Revises: c1173f955173
Create Date: 2025-08-01 03:16:53.930787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81df6892ff08'
down_revision = 'c1173f955173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.alter_column('watched_on',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.alter_column('watched_on',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
