"""Initial migration with Watch fields

Revision ID: c1173f955173
Revises: 
Create Date: 2025-08-01 02:14:52.307815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1173f955173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('watched_on',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.TEXT(), nullable=True))
        batch_op.alter_column('watched_on',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('rating')
        batch_op.drop_column('genre')
        batch_op.drop_column('year')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
